sudo: required
branches:
    only:
        - master
cache:
    pip: True
    directories:
      - node_modules
      - downloads
language: python
python:
    - "2.7"
services:
    - docker
    - memcached
    - mysql
env:
    matrix:
        - TOXENV=py27
          PIPELINE_SASS_BINARY=$TRAVIS_BUILD_DIR/node_modules/.bin/node-sass
          PIPELINE_CSS_COMPRESSOR=pipeline.compressors.cssmin.CSSMinCompressor
          PIPELINE_CSSMIN_BINARY=$TRAVIS_BUILD_DIR/node_modules/.bin/cssmin
          PIPELINE_JS_COMPRESSOR=pipeline.compressors.uglifyjs.UglifyJSCompressor
          PIPELINE_UGLIFYJS_BINARY=$TRAVIS_BUILD_DIR/node_modules/.bin/uglifyjs
          DATABASE_URL=mysql://root:@127.0.0.1:3306/kuma
          ES_VERSION=2.4.5
          ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/$ES_VERSION/elasticsearch-$ES_VERSION.tar.gz
        - TOXENV=flake8
        - TOXENV=docs
        - TOXENV=locales
          DOCKER_COMPOSE_VERSION=1.9.0
        - TOXENV=docker
          DOCKER_COMPOSE_VERSION=1.9.0
          UID=0
        - TOXENV=stylelint
matrix:
    allow_failures:
        - env: TOXENV=locales DOCKER_COMPOSE_VERSION=1.9.0
install:
    - nvm install 6
    - nvm use 6
    - scripts/travis-install
    - pip install -U pip
    - pip install -r requirements/travis.txt
    # Wait for ElasticSearch to be ready
    - if [ -n "$ES_DOWNLOAD_URL" ]; then wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200; fi;
script: tox -v
after_failure:
    - dmesg | tail
after_success:
    - codecov
notifications:
    irc:
        channels:
            - "irc.mozilla.org#mdndev"
        on_success: always
        on_failure: always
        use_notice: true
