#!/bin/bash
set -e
set -x
export LC_CTYPE=en_US.UTF-8

if [ "$TOXENV" == "docker" -o "$TOXENV" == "locales" ]
then
    curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    chmod +x docker-compose
    sudo mv docker-compose /usr/local/bin
fi
